version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - app-network

  activity-tracking:
    build:
      context: ./activity-tracking
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
    ports:
      - "5300:5300"
    depends_on:
      - mongodb
    networks:
      - app-network

  analytics:
    build:
      context: ./analytics
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://root:cfgmla23@mongodb:27017
    ports:
      - "5050:5050"
    depends_on:
      - mongodb
    networks:
      - app-network

  authservice:
    build:
      context: ./authservice
      dockerfile: Dockerfile
    environment:
      SPRING_DATA_MONGODB_DATABASE: test
      SPRING_DATA_MONGODB_URI: mongodb://root:cfgmla23@mongodb:27017
      JWT_SECRET: ${JWT_SECRET}
    env_file:
      - .env
    ports:
      - "8080:8080"

  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=cfgmla23
    ports:
      - "27017:27017"
    volumes:
      - mongodbdata:/data/db
    networks:
      - app-network

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - app-network

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodbdata:
