logging.level.org.springframework=DEBUG
logging.level.com.authservice=DEBUG

spring.data.mongodb.database=test
spring.data.mongodb.uri=mongodb://root:cfgmla23@localhost:27017

jwt.secret=${JWT_SECRET}

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always

# management.metrics.binders.processor.enabled=false
# management.metrics.binders.system.enabled=false
# management.metrics.enable.process=false
# management.metrics.enable.system=false
# management.metrics.enable.jvm=false