FROM gradle:7.2-jdk17

WORKDIR /home/gradle/src

COPY . .

RUN chmod +x gradlew

ENV JAVA_TOOL_OPTIONS="-Dmanagement.metrics.enable.process=false -Dmanagement.metrics.enable.system=false"

CMD ["./gradlew", "test", "--no-daemon"]