FROM gradle:7.2-jdk17

WORKDIR /home/gradle/src

COPY . .

RUN chmod +x gradlew

ENV SPRING_PROFILES_ACTIVE=test
ENV JAVA_TOOL_OPTIONS="-XX:-UseContainerSupport -Dmanagement.metrics.binders.processor.enabled=false -Dmanagement.metrics.binders.system.enabled=false"

CMD ["./gradlew", "test", "--no-daemon", "--info"]