name: CI Pipeline

on:
  pull_request:
    branches: [preprod]
    paths:
      - 'frontend/**'
      - 'activity-tracking/**'
      - 'authservice/**'
      - 'analytics/**'

jobs:

  frontend-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Build Frontend
        run: |
          cd frontend
          npm install
          npm run build

  activity-tracking-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.19.4

      - name: Install dependencies
        run: |
          cd activity-tracking
          npm install

      - name: Start application
        run: |
          cd activity-tracking
          npm start &


  authservice-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Build AuthService
        run: |
          cd authservice
          ./gradlew clean build

      - name: Run Tests
        run: |
          cd authservice
          ./gradlew test

  analytics-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Install Dependencies & Run Tests
        run: |
          cd analytics
          pip install -r requirements.txt
          pytest || true