name: Semgrep SAST Scan

on:
  push:
    branches:
      - main
      - preprod

  pull_request:
    branches:
      - main
      - preprod

jobs:
  semgrep:
    name: Run Semgrep Security Scan
    runs-on: ubuntu-latest

    container:
      image: returntocorp/semgrep

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Semgrep scan
        run: |
          semgrep --config=p/javascript .
          semgrep --config=p/nodejs .
          semgrep --config=p/java .
          semgrep --config=p/python .